ci: Collect Code Coverage
getsentry/sentry-rust pull request #295
Opened 2020-11-23 10:03 UTC by Swatinem

2021-01-07 10:53 UTC, flub reviewed
where can i see the coverage report?

2021-01-07 11:50 UTC, Swatinem commented
https://codecov.io/gh/getsentry/sentry-rust/tree/e958d9004397b2990cf1a28e9a66f72e15a4dafe
Jan suggested to pass the cargo test command invocation to fucov via the action variable, but I can do that in the action without breaking.

2021-01-29 11:52 UTC, jan-auer requested changes

2021-01-29 11:52 UTC, jan-auer commented on .github/workflows/ci.yml
> +      - uses: codecov/codecov-action@v1
Please pin this to the current SHA of the action until we approve codecov as trusted party.

2021-01-29 11:52 UTC, jan-auer commented on .github/workflows/ci.yml
> +      - uses: Swatinem/fucov@v1
Before merging this, can you please add an input to `fucov` to specify the cargo arguments that it runs with?

2021-03-01 07:36 UTC, jan-auer approved these changes
To confirm, this now runs the test suite twice: Once with and once without coverage?

2021-03-01 08:45 UTC, Swatinem commented
> To confirm, this now runs the test suite twice: Once with and once without coverage?

Yes, though this only runs on nightly linux

2021-03-01 08:46 UTC, merged